# This is a placeholder generated by `nixos-generate-config`.
# Replace with real hardware config on install, or generate per-host under
# nixconf/hosts/<host>/hardware-configuration.nix once hosts are added.
{ lib, ... }:

{
  # Minimal stub so `nix flake check` evaluates without real hardware.
  # Remove once a real hardware-configuration.nix is in place.
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  swapDevices = lib.mkDefault [ ];
}
